import gidrokos from '../image/gidrokos.png'
import mafon from '../image/mafon.png'
import verovka from '../image/verovka.png'
import binokl from '../image/binokl.png'
import jilet from '../image/jilet.png'
import rukzak from '../image/rukzak.png'
import drive from '../image/motor.png'

export const Goods = [
  {
    id: '1',
    name: 'Мужской костюм 3мм',
    price: 7000,
    likes: false,
    promotion: { sale: 0, new: false, hit: false, diler: 0 },
    basket: false,
    images: gidrokos,
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '2',
    name: 'BRP Audio-портативная система',
    price: 0,
    likes: false,
    promotion: { sale: 0, new: false, hit: false, diler: 0 },
    basket: false,
    images: mafon,
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '3',
    name: 'Спасательное снаряжение',
    price: 0,
    likes: false,
    promotion: { sale: 0, new: false, hit: false, diler: 0 },
    basket: false,
    images: verovka,
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '4',
    name: 'BRP Audio-Premium System',
    price: 68000,
    likes: false,
    promotion: { sale: 0, new: false, hit: false, diler: 0 },
    basket: false,
    images: binokl,
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '5',
    name: "Спасательный жилет BRP Men's Airflow PFD",
    price: 6900,
    likes: false,
    promotion: { sale: 0, new: false, hit: false, diler: 0 },
    basket: false,
    images: jilet,
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '6',
    name: 'Водонепроницаемый Рюкзак',
    price: 9800,
    likes: false,
    promotion: { sale: 0, new: false, hit: false, diler: 0 },
    basket: false,
    images: rukzak,
  },
  {
    id: '7',
    name: 'Лодочный мотор',
    brand: 'Suzuki DF9.9BRS',
    price: 225000,
    likes: false,
    promotion: { sale: 15.6, new: false, hit: false, diler: 0 },
    basket: false,
    images: drive,
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '8',
    name: 'Спасательное снаряжение-2',
    price: 100,
    likes: false,
    promotion: { sale: 10, new: false, hit: false, diler: 0 },
    basket: false,
    images: verovka,
    description: '6477311dj',
    comments: '12d7gb8k',
  },
]
