export const Goods = [
  {
    id: '1',
    name: 'Мужской костюм 3мм',
    price: 7000,
    likes: false,
    basket: false,
    images: 'gidrokos.png',
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '2',
    name: 'BRP Audio-портативная система',
    price: 0,
    likes: false,
    basket: false,
    images: 'mafon.png',
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '3',
    name: 'Спасательное снаряжение',
    price: 0,
    likes: false,
    basket: false,
    images: 'verovka.png',
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '4',
    name: 'BRP Audio-Premium System',
    price: 68000,
    likes: false,
    basket: false,
    images: 'binokl.png',
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '5',
    name: "Спасательный жилет BRP Men's Airflow PFD",
    price: 6900,
    likes: false,
    basket: false,
    images: 'jilet.png',
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '6',
    name: 'Водонепроницаемый Рюкзак',
    price: 9800,
    likes: false,
    basket: false,
    images: 'rukzak.png',
  },
  {
    id: '7',
    name: 'Лодочный мотор',
    brand: 'Suzuki DF9.9BRS',
    price: 225000,
    likes: false,
    basket: false,
    images: 'motor.png',
    description: '6477311dj',
    comments: '12d7gb8k',
  },
  {
    id: '8',
    name: 'Спасательное снаряжение-2',
    price: 100,
    likes: false,
    basket: false,
    images: 'verovka.png',
    description: '6477311dj',
    comments: '12d7gb8k',
  },
]
